package com.ledgerlab.audit;

public enum AuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    MEMBERSHIP_CREATED,
    MEMBERSHIP_ROLE_CHANGED,
    ACCOUNT_CREATED,
    ACCOUNT_STATUS_CHANGED,
    DEPOSIT_CREATED,
    TRANSFER_CREATED,
    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_FAILED,
    PAYMENT_CAPTURED,
    PAYMENT_VOIDED,
    PAYMENT_REFUNDED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    SETTLEMENT_IMPORTED,
    RECONCILIATION_COMPLETED
}
